apiVersion: batch/v1
kind: CronJob
metadata:
  name: puller-job
  namespace: shack
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 50
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: trust-bundle
            configMap:
              name: cm-trust-bundle
          containers:
          - name: puller
            image: quay.io/adjetstack/curlpine:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: trust-bundle
              mountPath: "/etc/trust"
              readOnly: true
            command:
              - /usr/bin/time
              - curl -L -o /tmp/out --cacert /etc/trust/trust.pem --proxy-cacert /etc/trust/trust.pem --proxy https://shack.shack.svc.cluster.local https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
                # - apk add curl ; curl -L -o /tmp/out --cacert /etc/trust/trust.pem --proxy-cacert /etc/trust/trust.pem --proxy https://shack.shack.svc.cluster.local https://speed.hetzner.de/1GB.bin
                #- apk add curl ; curl -L -o /tmp/out https://speed.hetzner.de/1GB.bin
          restartPolicy: OnFailure
