apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cm-trust-bundle
  namespace: shack
spec:
  sources:
  - configMap:
      name: "shack-root-cm"
      key: "root.crt"
  target:
    configMap:
      key: trust.pem
